name: saltstack-sudo-formula
source: https://github.com/bechtoldt/saltstack-sudo-formula
summary: SaltStack Formula to set up and configure sudo, a program to give limited root privileges to users
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - configure sudo
